ant_photo_rest_create:
    pattern: /photo
    defaults: { _controller: AntPhotoRestBundle:Photo:create }
    methods: [POST]
ant_photo_rest_delete:
    pattern: /photo/{id}
    defaults: { _controller: AntPhotoRestBundle:Photo:delete }
    methods: [DELETE]
ant_photo_rest_show:
    pattern: /photo/{id}
    defaults: { _controller: AntPhotoRestBundle:Photo:show }
    methods: [GET]   
    
    
ant_photo_rest_vote_create:
    pattern: /vote
    defaults: { _controller: AntPhotoRestBundle:Vote:create }
    methods: [POST]
ant_photo_rest_vote_delete:
    pattern: /vote/{photoId}
    defaults: { _controller: AntPhotoRestBundle:Vote:delete }
    methods: [DELETE]
ant_photo_rest_vote_show:
    pattern: /vote/{photoId}
    defaults: { _controller: AntPhotoRestBundle:Vote:show }
    methods: [GET]
ant_photo_rest_vote_show:
    pattern: /vote
    defaults: { _controller: AntPhotoRestBundle:Vote:votes }
    methods: [GET]
