ant_photo_rest_create:
    pattern: /{id}/photo
    defaults: { _controller: AntPhotoRestBundle:Photo:create }
    methods: [POST, OPTIONS]
ant_photo_rest_insert_to_album:
    pattern: /{user_id}/photos/{photo_id}/albums/{album_id}
    defaults: { _controller: AntPhotoRestBundle:Photo:insertToAlbum }
    methods: [POST]
ant_photo_rest_delete_of_album:
    pattern: /{user_id}/photos/{photo_id}/albums
    defaults: { _controller: AntPhotoRestBundle:Photo:deleteOfAlbum }
    methods: [DELETE]
ant_photo_rest_albums_user:
    pattern: /{id}/albums
    defaults: { _controller: AntPhotoRestBundle:Album:list }
    methods: [GET]
ant_photo_rest_album_user:
    pattern: /{user_id}/albums/{album_id}
    defaults: { _controller: AntPhotoRestBundle:Album:show }
    methods: [GET]

ant_photo_rest_vote_create:
    pattern: /{id}/vote
    defaults: { _controller: AntPhotoRestBundle:Vote:create }
    methods: [POST]
ant_photo_rest_vote_delete:
    pattern: /{id}/votes/{photo_id}
    defaults: { _controller: AntPhotoRestBundle:Vote:delete }
    methods: [DELETE]
ant_photo_rest_vote_all_show:
    pattern: /{id}/votes
    defaults: { _controller: AntPhotoRestBundle:Vote:votes }
    methods: [GET]
ant_photo_rest_vote_show:
    pattern: /{id}/photos/{photo_id}/votes
    defaults: { _controller: AntPhotoRestBundle:Vote:show }
    methods: [GET]