ant_photo_rest_create:
    pattern: /ant/photo
    defaults: { _controller: AntPhotoRestBundle:Photo:create }
    methods: [POST, PUT]
ant_photo_rest_delete:
    pattern: /ant/photo/{id}
    defaults: { _controller: AntPhotoRestBundle:Photo:delete }
    methods: [DELETE]
