ant_photo_rest_create:
    pattern: /{id}/photo
    defaults: { _controller: AntPhotoRestBundle:Photo:create }
    methods: [POST]
ant_photo_rest_delete:
    pattern: /{user_id}/photo/{photo_id}
    defaults: { _controller: AntPhotoRestBundle:Photo:delete }
    methods: [DELETE]
ant_photo_rest_show_me_all:
    pattern: /{id}/photos
    defaults: { _controller: AntPhotoRestBundle:Photo:photos }
    methods: [GET]


    
ant_photo_rest_vote_create:
    pattern: /{id}/vote
    defaults: { _controller: AntPhotoRestBundle:Vote:create }
    methods: [POST]
ant_photo_rest_vote_delete:
    pattern: /{id}/vote/{photo_id}
    defaults: { _controller: AntPhotoRestBundle:Vote:delete }
    methods: [DELETE]
ant_photo_rest_vote_all_show:
    pattern: /{id}/vote
    defaults: { _controller: AntPhotoRestBundle:Vote:votes }
    methods: [GET]
