parameters:
    ant.photo_rest.upload.photo_uploader: Ant\PhotoRestBundle\Upload\PhotoUploader

services:
    ant.photo_rest.upload.photo_uploader:
        class: %ant.photo_rest.upload.photo_uploader%
        arguments: [@image_adapter_fs, @image_resizer.resizer, %ant.photo_rest.upload.thumbnails%]