ant_photo_rest_show_user_all:
    pattern: /users/{id}/photos
    defaults: { _controller: AntPhotoRestBundle:Photo:photosUser }
    methods: [GET]
ant_photo_rest_show:
    pattern: /photos/{id}
    defaults: { _controller: AntPhotoRestBundle:Photo:show }
    methods: [GET]
ant_photo_rest_album_create:
    pattern: /users/{id}/albums
    defaults: { _controller: AntPhotoRestBundle:Album:create }
    methods: [POST]
ant_photo_rest_album_delete:
    pattern: /users/{user_id}/albums/{album_id}
    defaults: { _controller: AntPhotoRestBundle:Album:delete }
    methods: [DELETE]
ant_photo_rest_delete:
    pattern: /photos/{photo_id}
    defaults: { _controller: AntPhotoRestBundle:Photo:delete }
    methods: [DELETE]
ant_photo_rest_photos_album:
    pattern: /albums/{album_id}/photos
    defaults: { _controller: AntPhotoRestBundle:Photo:photosAlbum }
    methods: [GET]